### ISSUE TITLE
Issue with GremlinMethod as ClassMethod

### ISSUE THREAD

**Issue by Goldcap** [platinummonkey/mogwai#20]
I'm using Python 2.7, TItan 0.5.4, and just did a copy/paste of the code here, and got the "transaction is not open" error. We may need to update the docs, (I might have missed something) or perhaps there is something we need to modify, not sure I can tell which :)

http://mogwai.readthedocs.org/en/latest/examples/example_groovy_imports.html

Noting that I have a ton of other stuff in use, including a GremlinMethod with property=True, it's just the classmethod that seems to have an issue. Stack trace is:

```
$ python contact/titan.py
Traceback (most recent call last):
  File "contact/titan.py", line 18, in <module>
    result1, result2 = Trinket.test_method(1, 2)
  File "/mnt/Primary/venvs/wishlist/lib/python2.7/site-packages/mogwai/models/element.py", line 496, in method_wrapper
    return method(self, *args, **kwargs)
  File "/mnt/Primary/venvs/wishlist/lib/python2.7/site-packages/mogwai/gremlin/base.py", line 276, in __call__
    results = super(GremlinMethod, self).__call__(instance, *args, **kwargs)
  File "/mnt/Primary/venvs/wishlist/lib/python2.7/site-packages/mogwai/gremlin/base.py", line 205, in __call__
    tmp = connection.execute_query(script, params, context=context, **query_kwargs)
  File "/mnt/Primary/venvs/wishlist/lib/python2.7/site-packages/mogwai/metrics/manager.py", line 152, in wrapper
    return fn(*args, **kwargs)
  File "/mnt/Primary/venvs/wishlist/lib/python2.7/site-packages/mogwai/connection.py", line 51, in execute_query
    response = get_response(query, params=params, isolate=isolate, transaction=transaction, connection=conn, connection_pool=connection_pool)
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/mnt/Primary/venvs/wishlist/lib/python2.7/site-packages/rexpro/connectors/base.py", line 134, in connection
    yield conn
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/mnt/Primary/venvs/wishlist/lib/python2.7/site-packages/rexpro/connectors/base.py", line 387, in transaction
    self.close_transaction(False)
  File "/mnt/Primary/venvs/wishlist/lib/python2.7/site-packages/rexpro/connectors/base.py", line 281, in close_transaction
    raise exceptions.RexProScriptException("transaction is not open")
rexpro.exceptions.RexProScriptException: transaction is not open
```

**Comment by platinummonkey** [comment]
Thanks! updated the docs, RTD will update shortly

there was an error in the example script, it should be "return [a1, a2]"
